"""Curated engine/library meanings. Only what scripts or DF.EXE support.

confidence:
  proven-scripts — control flow in extracted Dust scripts shows this
  inferred     — very likely from usage, not proven in DF.EXE
  unknown      — still a reconstruction gap
"""

from __future__ import annotations

# dfextract .txt currently prints Titanic 4.0 names. Dust DF.EXE uses the
# second name for the same id. Agents reading .txt must apply this map.
EXTRACT_TXT_ALIASES: dict[int, tuple[str, str]] = {
    12007: ("makecricket", "makeball"),
    12012: ("stopcricket", "stopball"),
    12037: ("paintingscript", "floorscript"),
    12066: ("sendtopainting", "sendtofloor"),
    16011: ("currentview", "currentdir"),
    16034: ("currentcd", "actorhitbox"),
    16047: ("pausecricket", "pauseball"),
    20011: ("iscricket", "isball"),
    20017: ("pointinpainting", "setwidth"),
    20018: ("countpaintings", "setheight"),
    20021: ("sendtopostfx", "rowcoltoscene"),
    20022: ("indextopainting", "scenefloor"),
    20023: ("actorexists", "scenerow"),
    20024: ("propexists", "scenecol"),
    20067: ("fileexists", "findfile"),
    20082: ("calcmod", "cacheinfo"),
    20090: ("sendtopaintingfx", "sendtofloorfx"),
    20100: ("sendtoserverfx", "scenebuild"),
    20101: ("indextocricket", "indextoball"),
    20104: ("countcrickets", "countballs"),
}

# Engine-called procedure names (not opcodes). Dust looks these up by string.
HOOKS = {
    "boot": "BOOTFILE start. Sets paths, clock, plays intros, opens casts/shops.",
    "keydown": "Keyboard. Boot dispatches to the visible set/flat. arg is a key name (`uparrow`, …).",
    "keyrepeat": "Boot wraps keydown and sets isrepeat.",
    "mousedown": "Click. Boot hit-tests, then sendto* the object. arg is a point.",
    "setcursor": "Hover. Same dispatch as mousedown; sets cursor art.",
    "idle": "Boot idle tick. Updates cursor via hittest.",
    "openset": "SET load hook (per location).",
    "closeset": "SET unload hook.",
    "offerobject": "Use-item-on-world hook. Often empty.",
    "runyoself": "Puppet conversation entry. Almost every PUP day script starts here.",
    "menuselect": "Menu item by string (`quit`, `volume 3`, …).",
}

# Game-authored library (not DF.EXE). Defined in FLT/_NEW (new.flt) unless noted.
LIBRARY = {
    "spotmovie": {
        "defined_in": "FLT/_NEW (openstagefile \"new.flt\")",
        "summary": "Fade out, playmovie(name), fade back to set or puppet.",
        "args": "filename string (`apothpig.mov`)",
        "notes": [
            "Not an opcode. SET scripts write sendtostage (spotmovie (\"….mov\")).",
            "Engine verb underneath is playmovie.",
            "One premovie/postmovie wrap. playmovie itself follows MOV rec+0x16==3 (towerup → towertop → towerdn) so the fades bracket the whole chain, not each reel.",
        ],
    },
    "gototown": {
        "defined_in": "FLT/_NEW",
        "summary": "Leave an interior for the street. Night (clock=3) loads nite.set, else town.set. Restores townscene.",
        "args": "facing string (`north`, currentview(), …)",
    },
    "gotointerior": {
        "defined_in": "FLT/_NEW",
        "summary": "If current set is town, remember townscene, then opensetfile the interior.",
        "args": "set filename (`school.set`, `nitescho.set`, …)",
    },
    "gotospecial": {
        "defined_in": "FLT/_NEW",
        "summary": "Fade, closesetfile, opensetfile, optional currentscene/currentview, blacktoscreen.",
        "args": "setname, scenename, dirname (empty string = skip)",
    },
    "advanceday": {
        "defined_in": "FLT/_NEW",
        "summary": "Advances clock, or day when clock was 3. Plays day-change movies, inits sets, resets a lot of globals. Boot calls sendtostage (advanceday ()) after setting day=1 clock=2 phase=1 — that forces the first-slot setup (clock becomes 3 on day 1).",
        "args": "none",
        "notes": [
            "Day 1 start cash is 5 (999 if debugging).",
            "Help help.16 (“Here! Five dollars. A loan…”) is if playercash <= 0, not the spawn grant. Dump: PUP/_HELP1/day1.txt:9 (same on Help2).",
            "Day-change MOV names are d1nd2m, d2md2a, d2ad2n, …",
        ],
    },
    "initall": {
        "defined_in": "FLT/_NEW",
        "summary": "Stop loops/walks, switch SET, re-init gang actors and inven props.",
        "args": "logical set name, file to opensetfile",
    },
    "canadvance": {
        "defined_in": "FLT/_NEW",
        "summary": "Whether the player is allowed to sleep/advance this slot. Encodes item gates (gun/boots/bullets on day 2 morning, ring+pages day 3, mask+yunnibook+flute later).",
        "args": "none",
        "returns": "true/false",
    },
    "addinven": {
        "defined_in": "PRP/_INVEN",
        "summary": "Put an item in inventory. Boot gives helpbut at start.",
        "args": "item id string (`cards`, `gun`, `helpbut`, …)",
    },
}

# High-value DF.EXE opcodes. `id` is the Dust table id (None if unknown).
OPCODES: list[dict] = [
    {
        "name": "puppetspeak",
        "id": 12043,
        "summary": "Play a puppet dialogue line (audio + face). Scripts stack several in a row with no wait loop, unlike voicesound.",
        "args": "line id string (`jenix.5`, `jones.1`). Rarely a second integer (Jones: puppetspeak (\"jones.33\", 101) in place of a bevel).",
        "returns": "none (command band)",
        "blocking": "inferred yes — sequential conversation would break if it returned immediately",
        "confidence": "inferred",
        "notes": [
            "Almost always one string. Maps to PUP/_NAME/AUDIO/*.wav + texts.csv.",
            "Compare voicesound: scripts poll currentvoice() != \"none\". puppetspeak is never polled that way.",
        ],
    },
    {
        "name": "puppetclear",
        "id": 12041,
        "summary": "Clear the current speech/choice UI before offering a new bevel set.",
        "args": "none",
        "returns": "none",
        "blocking": "inferred no",
        "confidence": "proven-scripts",
        "notes": [
            "Jones/Jenix always puppetclear() then one or more puppetbevel() then puppetevent().",
        ],
    },
    {
        "name": "puppetbevel",
        "id": 12044,
        "summary": "Register one dialogue choice. Does not wait. Ids are later returned by puppetevent.",
        "args": "label string, choice id integer",
        "returns": "none",
        "blocking": "no — several bevels are issued, then one puppetevent",
        "confidence": "proven-scripts",
        "notes": [
            "Jenix: puppetbevel (\"Yes, here is the money.\", 101) then case 101.",
            "Jones uses 101–104 as topic ids. 55555 is the inventory-hand bevel (with addhandbevel), not a spoken line.",
            "Duplicate ids in one menu are legal (Jones subrack1 offers two lines both as 101).",
        ],
    },
    {
        "name": "puppetevent",
        "id": 20028,
        "summary": "Wait for the player to pick a bevel (or dismiss). Returns that id.",
        "args": "always (-1) in Dust",
        "returns": "integer: choice id, or -1 dismiss, or 55555 inventory bevel",
        "blocking": "yes",
        "confidence": "proven-scripts",
        "notes": [
            "arg = puppetevent (-1) then switch arg / case -1 / case 101 …",
            "Meaning of the -1 argument is unproven in DF.EXE (sentinel / timeout / allow-dismiss). Do not invent other values; Dust always passes -1.",
        ],
    },
    {
        "name": "plugin",
        "id": 12027,
        "summary": "Call a native plugin for side effect (no value used).",
        "args": "verb string, then plugin-specific args",
        "returns": "none",
        "blocking": "unknown",
        "confidence": "proven-scripts",
        "notes": [
            "Boot debug menu: plugin (\"writestats\", \"gblw\").",
            "CHECKERS.DLL exports PlugProc only; the verb string is dispatched inside the DLL.",
        ],
    },
    {
        "name": "pluginfx",
        "id": 20098,
        "summary": "Call a native plugin and use the return value.",
        "args": "verb string, then plugin-specific args",
        "returns": "whatever the plugin returns (checkers: a string)",
        "blocking": "unknown",
        "confidence": "proven-scripts",
        "notes": [
            "move = pluginfx (\"checkmove\", mainboard, count, 0)",
            "playerjumps = pluginfx (\"checkmove\", mainboard, 0, 1)",
            "Empty string means no moves (AI loss / no jumps).",
            "Returned move list is comma-separated row/col/code triples (trailing comma). Codes 1-4 jump, 5-8 step. findword(list, \",\", n) then findword(word, \"\", 3).",
            "Mode 0 = him AI minimax (lookahead ply, no alpha-beta). Mode 1 lookahead 0 = player jump list.",
            "Player-legal step/jump tests also exist in PRP/_CHECKERS scripts (goodmove/goodjump). Play copy of the DLL is src/play/checkers.ts.",
            "automove keeps the comma list in global move; makemove (move, person) reassigns its parameter to the decoded delta. That assignment is local — writing the global made delrow the packed triple and writeboard padded mainboard off the 8x8.",
        ],
    },
    {
        "name": "playmovie",
        "id": 12017,
        "summary": "Play a MOV file (full-screen cutscene). Engine verb.",
        "args": "filename string (`intro.mov`, `d2md2a.mov`, …)",
        "returns": "none",
        "blocking": "inferred yes (boot plays intro then intro2 in order; spotmovie wraps it with fades)",
        "confidence": "inferred",
        "notes": [
            "Still holds: 80-byte records at MOV header+0x8C2. Tick = timeGetTime()*3/50 (60 Hz). See findings.md §7.",
            "Group A (header+0x1A): start when record+32 equals the 1-based slot; retrigger restarts that slot.",
            "rec+0x1A bit 0: after start_A, busy-wait mixer channel 0 idle (DF.EXE 0x419300). Extract wait_audio. dog1 recs 2 and 4; 75 reels in this install. INTRO2 A2 retriggers do not set it.",
            "A new scene’s A line is held until the previous scene’s A line’s original end (INTRO clip 325 vs 423).",
            "Group B (header+0x1C): sequential theme playlist at +0x83E; a scene with n_b=0 keeps the previous bed.",
            "Stills are deltas into one framebuffer. Scene headers are not images — keep prior pixels.",
            "Each scene header loads a 256-entry palette at +0x3E. RGB/PNG must use that palette.",
            "When rec+0 cmd count is 0, rec+0x16==3 copies rec+0x30 Pascal and continues (0x419a24). Scripts name only towerup.mov; playmovie chains towertop.mov then towerdn.mov. intro2.mov chains intro3.mov the same way; intro.mov does not (boot names intro2).",
            "Type-4 command (48 bytes, Mac rect + Pascal .mov at +16) pushes a nested playmovie (0x419ba3, depth < 5). TOWERTOP rec 2 windows are bellmoon / bellbarn / belltown.",
        ],
    },
    {
        "name": "opensetfile",
        "id": 12032,
        "summary": "Load a SET (location). Library gotospecial calls this after closesetfile.",
        "args": "filename (`town.set`, `nite.set`, `hotroom.set`, …)",
        "returns": "none",
        "blocking": "inferred yes",
        "confidence": "proven-scripts",
    },
    {
        "name": "closesetfile",
        "id": 12033,
        "summary": "Unload the current SET.",
        "args": "none in library use",
        "returns": "none",
        "confidence": "proven-scripts",
    },
    {
        "name": "sendtostage",
        "id": 12070,
        "summary": "Run an expression in the stage (open FLT / new.flt) context.",
        "args": "a call, e.g. spotmovie (\"x.mov\"), advanceday (), gotointerior (\"school.set\")",
        "returns": "none",
        "confidence": "proven-scripts",
        "notes": [
            "This is message-send, not a file load. The first argument is the thing to run, not a filename.",
            "sendtoactor/prop/scene/flat/shop/cast/set/button/boot are the same idea with different namespaces.",
        ],
    },
    {
        "name": "sendtoactor",
        "id": 12016,
        "summary": "Run an expression on a named actor (cast member).",
        "args": "actor name string, then a call (mousedown, setupactor, putdownactor, resetactor, …)",
        "returns": "none",
        "confidence": "proven-scripts",
        "notes": [
            "Names are short (`JENIX`, `watson`, `bolivar`), not `jenix.pup`.",
            "setupactor/putdownactor/resetactor are user procedures on CST scripts, not opcodes.",
        ],
    },
    {
        "name": "sendtopuppet",
        "id": 12045,
        "summary": "Run an expression on the current/named puppet.",
        "args": "see call sites",
        "returns": "none",
        "confidence": "inferred",
    },
    {
        "name": "sendtoset",
        "id": 12067,
        "summary": "Run an expression on the current SET.",
        "args": "a call",
        "confidence": "inferred",
    },
    {
        "name": "sendtoshop",
        "id": 12059,
        "summary": "Run an expression on a PRP shop (inventory is `inven`).",
        "args": "shop name, then a call (addinven, addhandbevel, initprops, …)",
        "confidence": "proven-scripts",
    },
    {
        "name": "sendtocast",
        "id": 12048,
        "summary": "Broadcast to a CST (`gang`, `extra`).",
        "args": "cast name, then a call (initactors, …)",
        "confidence": "proven-scripts",
    },
    {
        "name": "sendtoscene",
        "id": 12034,
        "summary": "Run an expression on a SET scene (tile).",
        "args": "scene name or currentscene(), then a call",
        "confidence": "proven-scripts",
        "notes": ["Boot: sendtoscene (currentscene (), keydown (arg))."],
    },
    {
        "name": "sendtoprop",
        "id": 12055,
        "summary": "Run an expression on a named prop.",
        "args": "prop name, then a call",
        "confidence": "proven-scripts",
    },
    {
        "name": "sendtoflat",
        "id": 12069,
        "summary": "Run an expression on a FLT (`flat 0`, currentflat(), mainpanel).",
        "args": "flat name, then a call",
        "confidence": "proven-scripts",
    },
    {
        "name": "sendtoboot",
        "id": 12081,
        "summary": "Run an expression in boot context.",
        "args": "a call",
        "confidence": "inferred",
    },
    {
        "name": "hittest",
        "id": 20070,
        "summary": "What is under a point? Stores the kind in result() and returns the object name.",
        "args": "point",
        "returns": "object name string; kind is result() = actor|prop|button|scene|flat|none",
        "confidence": "proven-scripts",
        "notes": [
            "Boot mousedown: thename = hittest (thepoint) / switch result ().",
        ],
    },
    {
        "name": "result",
        "id": 16010,
        "summary": "Kind of the last hittest (and possibly other queries).",
        "args": "none when used as result ()",
        "returns": "string kind",
        "confidence": "proven-scripts",
    },
    {
        "name": "pointx",
        "id": 20002,
        "summary": "X of a point, in still pixels. Dust stills are 512 wide.",
        "args": "point (mousedown/setcursor arg, or mouse())",
        "returns": "integer",
        "confidence": "proven-scripts",
        "notes": [
            "Scene A2: pointx (arg) > 228 & pointx (arg) < 299 — exclusive bounds.",
            "Boot: pointx > 512 → right, < 0 → left (click off the plate turns).",
        ],
    },
    {
        "name": "pointy",
        "id": 20003,
        "summary": "Y of a point, in still pixels. Outdoor stills are 512×264.",
        "args": "point",
        "returns": "integer",
        "confidence": "proven-scripts",
        "notes": [
            "Boot: pointy < 0 → uparrow (walk). Click above the plate walks forward.",
        ],
    },
    {
        "name": "pointinprop",
        "id": 20040,
        "summary": "Is the point inside a named prop sprite?",
        "args": "prop name, point",
        "returns": "true/false",
        "confidence": "proven-scripts",
    },
    {
        "name": "pointinset",
        "id": 20041,
        "summary": "Is the point inside the SET view (the 512×264 plate)?",
        "args": "point",
        "returns": "true/false",
        "confidence": "proven-scripts",
    },
    {
        "name": "mouse",
        "id": 20006,
        "summary": "Current pointer as a point (idle cursor path).",
        "args": "none",
        "returns": "point",
        "confidence": "proven-scripts",
    },
    {
        "name": "cursor",
        "id": 12039,
        "summary": "Set cursor art by name.",
        "args": "string: arrow, touch, watch, sight, gostrait, goleft, goright, …",
        "returns": "none",
        "confidence": "proven-scripts",
        "notes": ["Bitmaps themselves are not in the script. UI chrome is still a gap."],
    },
    {
        "name": "actorowner",
        "id": 16043,
        "summary": "Get or set an actor flag/owner string (memory).",
        "args": "actor, value  → set.  actor only → get (usage-dependent)",
        "confidence": "proven-scripts",
        "notes": [
            "Jenix: actorowner (\"JENIX\", \"gavemoney\") after paying.",
            "Units/flag vocabulary are script strings, not enums in DF.EXE.",
        ],
    },
    {
        "name": "actorstar",
        "id": 16006,
        "summary": "Place an actor at a named star/waypoint.",
        "args": "actor, star expression",
        "confidence": "proven-scripts",
        "notes": [
            "A star is a named SET pin, not a sprite.",
            "Jenix refuse-money: actorstar (\"JENIX\", \"town.extra\" @ numtostring (random (3))).",
            "@ is string concat. town.extra + \"0\"/\"1\"/\"2\" indexes EXTRA CST extras.",
            "Waypoint units in SET JSON are 255 per tile — star names live in waypoints.json.",
            "50-byte SET records hold two stars. town.leroy1 is slot B of town.leroy2 at (1740, 3536). town.leroy2 (2656, 2720) is the range.",
        ],
    },
    {
        "name": "actorxyz",
        "id": 16003,
        "summary": "Actor position. Field band — likely get/set.",
        "args": "see call sites",
        "confidence": "unknown",
        "notes": ["Do not assume world units without a call site."],
    },
    {
        "name": "walktostar",
        "id": 12006,
        "summary": "Walk an actor to a named star, or beeline to an x,y,z string.",
        "args": "actor, star name or \"x,y,z\"",
        "blocking": "async walk; scripts wait with while iswalk { forceupdate }",
        "confidence": "proven-scripts",
        "notes": [
            "Named dest: DF.EXE 0x424000 loads the SET polyline at waypoint-record +0x18 (a container of {x,y,z,seg} int16s). Reverse when going slot B→A. Dust scripts never call walkonroad.",
            "town.leroy2/leroy1 is container 262: range (2656,2720) … (1664,3476) … sign (1740,3536). Walkout reverses that. No path pair is a beeline to the star xyz.",
            "Explicit x,y,z (town walktopuppet) is a beeline. actorspeed is world units per game frame. Boot framerate (3) waits 3 ticks of the 60 Hz timeGetTime counter (0x40e1d2) → 20 Hz, town stdspeed 3 → 60 units/s. CST walk pose table is setInfo +0x2e, length +0x70 (Leroy 16 slots, two frames per pose).",
        ],
    },
    {
        "name": "path",
        "id": 16009,
        "summary": "Virtual search path. Slot get/set. `@` concatenates path pieces.",
        "args": "path (n) → get slot n.  path (n, string) → set slot n.",
        "confidence": "proven-scripts",
        "notes": [
            "Boot: path (1, path (1) @ \"local:\"), path (2, \"dust:data:\"), path (3, \"dust:movies:\"), path (4, \"dust:puppets:\"), path (5, \"dust:under:\"), path (8, \"dust:inven:\").",
            "findfile/fileexists uses these slots. Browser remake maps them to dfextract/out/.",
        ],
    },
    {
        "name": "findfile",
        "id": 20067,
        "summary": "True if a game file exists on the virtual path. Extracted txt prints fileexists.",
        "args": "filename (`town.set`)",
        "returns": "true/false",
        "confidence": "proven-scripts",
        "notes": ["Boot refuses to run if not findfile (\"town.set\")."],
    },
    {
        "name": "@",
        "id": 8007,
        "summary": "String concat.",
        "args": "infix: a @ b",
        "returns": "string",
        "confidence": "proven-scripts",
        "notes": ["path (1) @ \"local:\", \"town.extra\" @ numtostring (random (3))."],
    },
    {
        "name": "me",
        "id": 4026,
        "summary": "Language value: the current object in some sendto/plugin contexts.",
        "args": "none (token, not a call)",
        "confidence": "inferred",
        "notes": ["Checkers win (\"me\") is a user function argument, not this token."],
    },
    {
        "name": "target",
        "id": 4027,
        "summary": "The object a sendto* is currently addressing.",
        "args": "none (token)",
        "confidence": "proven-scripts",
        "notes": ["INVEN setcursor: propview (target) = \"small\"."],
    },
    {
        "name": "passcode",
        "id": 4025,
        "summary": "Fall through: let the engine/default handler continue this event.",
        "args": "none (token)",
        "confidence": "inferred",
        "notes": [
            "SET mousedown/setcursor: after handling a hotspot, exitcode; otherwise passcode.",
            "Opposite of exitcode (stop this procedure).",
        ],
    },
    {
        "name": "exitcode",
        "id": 4005,
        "summary": "Return from the current `code` block immediately.",
        "args": "none (token)",
        "confidence": "proven-scripts",
        "notes": ["case -1 on puppetevent → exitcode (player dismissed talk)."],
    },
    {
        "name": "return",
        "id": 4024,
        "summary": "Return a value from the current `code` block.",
        "args": "expression (`return true`, `return (count)`)",
        "confidence": "proven-scripts",
    },
    {
        "name": "error",
        "id": 12053,
        "summary": "Abort / debugger trap on impossible switch fallthrough.",
        "args": "none",
        "confidence": "inferred",
        "notes": ["canadvance and checkers decodemove call error () if no case matched."],
    },
    {
        "name": "savegame",
        "id": 12077,
        "summary": "Write a save. Format unknown.",
        "args": "title string (`Dust 0.3`) in the quit menu",
        "confidence": "proven-scripts",
        "notes": ["Boot menuselect quit may questiondialog then savegame. Do not invent the file layout."],
    },
    {
        "name": "opengame",
        "id": 12078,
        "summary": "Load a save. Format unknown.",
        "args": "see call sites",
        "confidence": "unknown",
    },
    {
        "name": "dumpglobal",
        "id": 4029,
        "summary": "Debug print a global. Also used to list checkers state.",
        "args": "variable name, often without parens: dumpglobal mainboard",
        "confidence": "proven-scripts",
    },
    {
        "name": "code",
        "id": 4001,
        "summary": "Start a procedure. First token of every script container.",
        "args": "name (args)",
        "confidence": "proven-scripts",
        "notes": ["Pairs with endcode. Nested code is not used; new procedures are sequential in the file."],
    },
    {
        "name": "if",
        "id": 4006,
        "summary": "Conditional. Closed by endif. Optional else.",
        "args": "condition expression. Parens optional in some files.",
        "confidence": "proven-scripts",
    },
    {
        "name": "switch",
        "id": 4009,
        "summary": "Switch. case / endswitch. case bodies do not fall through in Dust usage (each case exits or ends).",
        "args": "expression. `switch (arg)` or `switch arg`.",
        "confidence": "inferred",
        "notes": ["Whether case falls through is unproven in DF.EXE. Dust scripts treat cases as exclusive."],
    },
    {
        "name": "global",
        "id": 4002,
        "summary": "Declare globals (persist across procedures / save).",
        "args": "comma-separated names",
        "confidence": "proven-scripts",
        "notes": [
            "Boot declares day, clock, phase, handitem, …",
            "A parameter of the same name is still a local of that proc. Assignment does not clobber the global (checkers `makemove (move)` vs `automove` `global move`).",
        ],
    },
    {
        "name": "local",
        "id": 4003,
        "summary": "Declare locals for this procedure.",
        "args": "comma-separated names",
        "confidence": "proven-scripts",
    },
    {
        "name": "true",
        "id": 4021,
        "summary": "Boolean constant (opcode, not a variable).",
        "confidence": "proven-scripts",
    },
    {
        "name": "false",
        "id": 4022,
        "summary": "Boolean constant (opcode, not a variable).",
        "confidence": "proven-scripts",
    },
    {
        "name": "framerate",
        "id": 16022,
        "summary": "Boot calls framerate (3). hasattention uses (seconds * 60) / framerate() frames.",
        "args": "integer",
        "confidence": "inferred",
        "notes": [
            "hasattention implies script frames at 60/framerate Hz (20 Hz when boot set 3).",
            "Do not treat 3 as 3 fps. SET walker fps is separate.",
        ],
    },
    {
        "name": "delay",
        "id": 12004,
        "summary": "Wait some ticks. Unit unknown (boot blacktoscreen uses 30; checkers delay (45)).",
        "args": "integer",
        "blocking": "inferred yes",
        "confidence": "inferred",
    },
    {
        "name": "makeloop",
        "id": 12005,
        "summary": "One-shot timer: after delay script frames, run proc on kind/who. Proc re-arms.",
        "args": "kind (`actor`/`prop`/`scene`/`flat`), who, proc name, delay frames",
        "confidence": "inferred",
        "notes": [
            "Leroy: makeloop (\"actor\", me, \"leroyidle\", 20); drink holds via toidle at 25.",
            "stoploop (kind, who) cancels. One loop per kind+who (later makeloop replaces).",
            "Delay uses the same script frames as hasattention (60/framerate).",
        ],
    },
    {
        "name": "stoploop",
        "id": 12011,
        "summary": "Cancel makeloop for that kind/who. who can be `all`.",
        "args": "kind, who",
        "confidence": "inferred",
    },
    {
        "name": "voicesound",
        "id": 12026,
        "summary": "Start a voice clip. Asynchronous: scripts wait with while currentvoice () != \"none\".",
        "args": "line id (`bol.102`)",
        "blocking": "no",
        "confidence": "proven-scripts",
    },
    {
        "name": "currentvoice",
        "id": 20078,
        "summary": "Playing voice id, or \"none\".",
        "args": "none",
        "returns": "string",
        "confidence": "proven-scripts",
    },
    {
        "name": "currentdir",
        "id": 16011,
        "summary": "Facing. Extracted txt prints currentview.",
        "args": "get: none. set: `north`/`south`/`east`/`west`/`strait`/`left`/`right` depending on caller",
        "confidence": "proven-scripts",
        "notes": [
            "SET boot keydown: currentscene (\"strait\"/\"left\"/\"right\") — those are walk/turn commands on the scene, not compass.",
            "gotospecial sets currentview (dirname) to a compass word.",
        ],
    },
    {
        "name": "currentscene",
        "id": 16029,
        "summary": "Get/set the SET tile (`scene g15`, `scene a1`) or issue a walk/turn (`strait`, `left`, `right`).",
        "args": "optional string",
        "confidence": "proven-scripts",
    },
    {
        "name": "clut",
        "id": 12038,
        "summary": "Palette / fade target named `black` or `set` or `puppet`.",
        "args": "string",
        "confidence": "inferred",
    },
    {
        "name": "blackscreen",
        "id": 12051,
        "summary": "Cut to black.",
        "args": "none",
        "confidence": "inferred",
    },
    {
        "name": "blacktoscreen",
        "id": 12049,
        "summary": "Fade up onto set/stage/puppet.",
        "args": "layer string (`set`, `stage`, `puppet`), duration integer",
        "confidence": "inferred",
    },
    {
        "name": "screentoblack",
        "id": 12050,
        "summary": "Fade down.",
        "args": "`current` plus duration, in library use",
        "confidence": "inferred",
    },
]


def opcode_fact(name: str) -> dict | None:
    for row in OPCODES:
        if row["name"] == name:
            return row
    return None
